### ISSUE TITLE
Not possible to view all app users in impersonation tab

### ISSUE THREAD

**Issue by plesatyaladin** [Chisyeuf/d365-sidepanel-dev-tools#2]
Hi, i cannot see all users in impersonate tab. Is it possible to change this behaviour?

I i understood, only users with security role are shown. This is not enough for our usage scenario:
- access is controlled by azure ad security group
- we have created dataverse teams based on ad security groups
- user will get security roles based on dataverse team, but user do not have directly assigned security role > that means no systemuserroles_association
- i believe this is the reason why user is not shown in impersonation list, however user has access to app

![image](https://github.com/user-attachments/assets/9f765826-6780-483e-ba9e-72bfb8d5538c)

**Comment by Chisyeuf** [comment]
Hello, thank you for your report.
This is a situation that I had not considered. I will work on a solution for your scenario.
